# Generated by Django 4.1.5 on 2023-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_of_production',
            name='reference_number',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
