# Generated by Django 4.1.5 on 2023-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_cost_of_production_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_of_production',
            name='reference_number',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
