# Generated by Django 4.1.5 on 2023-11-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_cost_of_production_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_transportation',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt_repayment',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixed_cost',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material_transportation',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening_stock',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_expenses',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_incomes',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other_transportation',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partial_sales',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piling_damages',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
