# Generated by Django 4.1.5 on 2023-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_block_transportation_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_type',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost_type',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance_type',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='particulars',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction_type',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportation_cost_detail',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportation_type',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='reference_number',
            field=models.CharField(default=1, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
