# Generated by Django 4.1.5 on 2023-11-26 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_block_type_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='Maintenance_Expense_List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('sub_maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.maintenance')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit')),
            ],
        ),
    ]
