# Generated by Django 4.1.5 on 2023-11-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_maintenance_quantity_remove_maintenance_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_expense_list',
            name='unit',
        ),
    ]
