# Generated by Django 4.1.5 on 2023-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_maintenance_expense_list_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_expense_list',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
