# Generated by Django 4.1.5 on 2023-12-02 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_maintenance_expense_list_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_expense_list',
            name='sub_maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.maintenance'),
        ),
    ]
