# Generated by Django 4.1.5 on 2023-12-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_maintenance_expense_list_sub_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_type',
            name='name',
            field=models.CharField(choices=[('Big Hollow', 'Big Hollow'), ('Small Hollow', 'Small Hollow'), ('Pavers', 'Pavers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenance_type',
            name='name',
            field=models.CharField(choices=[('BreakDown', 'Break Down'), ('Routine', 'Routine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction_type',
            name='name',
            field=models.CharField(choices=[('Partial', 'Partial'), ('Cash', 'Cash'), ('Credit', 'Credit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transportation_type',
            name='name',
            field=models.CharField(choices=[('Block', 'Block'), ('Material', 'Material'), ('Other', 'Other')], max_length=100),
        ),
    ]
