# Generated by Django 4.1.5 on 2023-12-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_block_type_name_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_expense_list',
            name='discount',
        ),
        migrations.AddField(
            model_name='maintenance_expense_list',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.unit'),
        ),
        migrations.AlterField(
            model_name='block_type',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenance_expense_list',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenance_expense_list',
            name='sub_maintenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.maintenance'),
        ),
        migrations.AlterField(
            model_name='maintenance_type',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction_type',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transportation_type',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
