# Generated by Django 4.1.5 on 2023-12-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_maintenance_expense_list_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance_expense_list',
            name='unit',
        ),
        migrations.AddField(
            model_name='maintenance_expense_list',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
