# Generated by Django 5.0 on 2024-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_maintenance_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_transportation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cost_of_production',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='debt_repayment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fixed_cost',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='material_transportation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_expenses',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_incomes',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='other_transportation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partial_sales',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
    ]
