# Generated by Django 5.0 on 2024-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_sales_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='currency',
        ),
        migrations.AddField(
            model_name='maintenance_expense_list',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
    ]
