# Generated by Django 5.0 on 2024-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_maintenance_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('SSP', 'SSP')], default='SSP', max_length=200, null=True),
        ),
    ]
